services:
  postgres:
    image: postgres:15-alpine
    container_name: healthshield-postgres
    environment:
      POSTGRES_DB: healthshield
      POSTGRES_USER: healthshield_user
      POSTGRES_PASSWORD: healthshield_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthshield_user -d healthshield"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - healthshield-network

  api:
    build: .
    container_name: healthshield-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Conexi√≥n a PostgreSQL
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: healthshield
      DB_USER: healthshield_user
      DB_PASSWORD: healthshield_password
      
      # Otras variables
      ENVIRONMENT: development
      DEBUG: "True"
      SECRET_KEY: RbwIHIbYL4J6h3PhdljFMgs9n
      ADMIN_PASSWORD: admin
      ALLOWED_ORIGINS: "*"
      PORT: 8000
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - healthshield-network

networks:
  healthshield-network:
    driver: bridge

volumes:
  postgres_data: